# Setup
title:        Hausa NLP
tagline:      Natural Language Processing
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Idris Abdulmumin
  url:        http://dcs.abu.edu.ng/staff/idris-abdulmumin 

# Gems
gems:
  - abumafrim

#Others
markdown: kramdown